# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pete's Messy Room
email: 
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Pete's blog! It's still in its beta stage and hopefully
  I can add more features to this in the near future. 
baseurl:  "" # the subpath of your site, e.g. /blog
url: "https://petetanru.github.io" # the base hostname & protocol for your site
github_username:  petetanru
linkedin_username: peeradej-pete-tanruangporn-0a977170
facebook_username: pete.tanruangporn

# Build settings
markdown: kramdown
