# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title:       pete's messy room
description: thoughts and notes

logo:  "/images/twister_royalblue.png"
cover: "/assets/img/cover.png"

baseurl: ""
url:     "https://petetanru.github.io"

owner:  Pete Peeradej Tanruangporn
rights: All Right Reserved


# Social & Sharing
# ----------------

google:
  analytics:
  verification:

facebook:
  username: pete.tanruangporn
  app_id:

twitter:
  username:
  large_img: sometimes

disqus:
  username: petetanru


# Content Format
# --------------

timezone: Asia/Bangkok
paginate: 10
mathjax:  true


# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

collections:
  projects:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

paginate_path: "/posts/page:num"

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []


