# Identity Setting
# ================
# you should change this to suit your own preference.

title:       Pete's Messy Room          #TODO title of this site
description: Beta-stage blog.            #TODO short description
logo:        "/images/twister_royalblue.png"         #TODO logo, recommended 256x256
cover:       "/images/cover.png"        #TODO cover, recommended 1200x630

baseurl:                                #TODO leaves blank if already root
url:     "https://petetanru.github.io"     #TODO canonical url w/ protocol

owner:  Pete Peeradej Tanruangporn      #TODO site's owner, individual or org
rights: All Right Reserved              #TODO rights statement

# Social & Sharing
# ----------------

google:
  analytics:                            #TODO e.g. U-8152342-4
  verification:                         #TODO verification string in meta tag

facebook:
  username: pete.tanruangporn                            #TODO site's facebook
  app_id:                               #TODO collect og sharing data

twitter:
  username:                             #TODO site's twitter
  share_large_image: true               #TODO use large img in twitter card

disqus:
  username: petetanru                            #TODO if polar.disqus.com, then polar


# Content Setting
# ===============
# you may change this to suit your own preference.

timezone: Asia/Bangkok                  #TODO post time offset
paginate: 10                             #TODO nos of excerpt post per page
mathjax:  true                          #TODO if true, write $ with \\$


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/posts/page:num"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate
